name: First Test Action
on: workflow_dispatch
jobs:
  first-one:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello First Step !"
      - name: Second Step
        run: echo "Hello Second Step !"
